# Desvincular el prefijo por defecto (Ctrl+b)
unbind C-b
# Definir el nuevo prefijo (Ctrl+a)
set-option -g prefix C-a
# Asegurar que se puede enviar Ctrl+a a otras aplicaciones
bind-key C-a send-prefix


# Permitir scroll
set -g mouse on

# Informacion de panel
set -g status-right "#[fg=black]IP: #(hostname -I | awk '{print $1}') #[fg=black]Ping: #(ping -c 1 -W 1 8.8.8.8 | grep 'time=' | awk -F'time=' '{print $2}' || echo 'Timeout') "

#set -g status-int
